package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Department;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int insert(Department row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int updateByPrimaryKey(Department row);
}