package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Position;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int insert(Position row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POSITION
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    int updateByPrimaryKey(Position row);
}