package lt.vu.mybatis.model;

import java.util.List;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEPARTMENT.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEPARTMENT.NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private String name;

    private List<Employee> employees;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEPARTMENT.ID
     *
     * @return the value of PUBLIC.DEPARTMENT.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEPARTMENT.ID
     *
     * @param id the value for PUBLIC.DEPARTMENT.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEPARTMENT.NAME
     *
     * @return the value of PUBLIC.DEPARTMENT.NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEPARTMENT.NAME
     *
     * @param name the value for PUBLIC.DEPARTMENT.NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }
}