package lt.vu.mybatis.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.LOGIN_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    private Integer departmentId;

    private Department department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.EMPLOYEE.FIRST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @param lastName the value for PUBLIC.EMPLOYEE.LAST_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.LOGIN_NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.LOGIN_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.LOGIN_NAME
     *
     * @param loginName the value for PUBLIC.EMPLOYEE.LOGIN_NAME
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @param departmentId the value for PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue May 03 08:19:10 EEST 2022
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Department getDepartment() {
        return this.department;
    }
}